language: cpp
sudo: true
before_install:
    - sudo apt-get -qq update
virtualenv:
  system_site_packages: true
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - g++-4.9
            - cmake
            - cmake-data
            - libcgal-dev
            - libeigen3-dev
            - libgmp-dev
            #- libumfpack5.6.2
            - python-numpy
            - python-scipy
            - python-setuptools
            - python
            - swig
script:
    - git submodule update --init --recursive
    - mkdir third_party/build
    - cd third_party/build
    - cmake -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 ..
    - make
    - make install
    - cd ../..
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 ..
    - make
    - make tools
    - ./setup.py build
    - ./setup.py install --user
env:
    - PYMESH_PATH=$TRAVIS_BUILD_DIR
after_success:
    - cd build
    - make all_tests
    - python -c "import pymesh; pymesh.test()"
