version: 2
jobs:
    build:
        docker:
            - image: debian:sid-slim
        steps:
            - checkout
            - run: |
                apt-get update
                apt-get install -y git gcc cmake libeigen3-dev libgmp-dev libgmpxx4ldbl libumfpack5 libmpfr-dev libboost-dev libboost-thread-dev python3-nose python3-numpy python3-scipy python3-setuptools swig && apt-get clean
            - run: git submodule sync
            - run: git submodule update --init
            - run:
                workding_directory: $CIRCLE_WORKING_DIRECTORY
                command: |
                    mkdir -p third_party/build
                    mkdir -p build
                    cd third_party/build
                    cmake .. && make -j 4 && make install
                    cd ../../build
                    cmake .. && make -j 4
                    make all_tests

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
