version: 2
jobs:
    dependencies:
        docker:
            - image: debian:sid-slim
        steps:
            - run: apt-get update
            - run: apt-get install -y git gcc cmake libeigen3-dev libgmp-dev libgmpxx4ldbl libumfpack5 libmpfr-dev libboost-dev libboost-thread-dev python3-nose python3-numpy python3-scipy python3-setuptools swig && apt-get clean
    build-third-party:
        docker:
            - image: debian:sid-slim
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: mkdir -p third_party/build
            - run: cd third_party/build
            - run: cmake .. && make -j 4 && make install
    build:
        docker:
            - image: debian:sid-slim
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: mkdir -p build
            - run: cd build
            - run: cmake .. && make -j 4
    test:
        docker:
            - image: debian:sid-slim
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: mkdir -p build
            - run: cd build
            - run: make all_tests

workflows:
    version: 2
    build_and_test:
        jobs:
            - dependencies
            - build-third-party:
                requires:
                    - dependencies
            - build:
                requires:
                    - build-third-party
            - test:
                requires:
                    - build
